### Config
title: Maxime Orefice
email: contact@maximeorefice.com
description: >-
  Tech, bon vivant, bitcoiner.

# Permalinks
permalink: pretty

# About
url: "https://maximeorefice.com"
twitter_username: goldenson_
github_username: goldenson

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-target-blank

relative_links:
  enabled: true
  collections: true

google_analytics: UA-152637440-1

exclude: ["Rakefile"]
