### Config

title: Maxime Orefice
email: orefice.maxime@gmail.com
description: >-
  French maker currently living in Canada. Curious human being who love to solve problems.
  On an eternal learning journey ✌️
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goldenson.dev"
twitter_username: goldenson_
github_username:  goldenson

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-webp
  - github-pages

google_analytics: UA-152637440-1

### Assets

webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff", ".gif"]
  gifs: [".gif"]
  regenerate: true
  webp_path: nil
  exclude: []
  append_ext: false