### Config
title: Maxime Orefice
email: contact@maximeorefice.com
description: >-
  Hacker, crossfiter, kiffeur, bitcoiner.

# Permalinks
permalink: pretty

# About
url: "https://maximeorefice.com"
twitter_username: goldenson_
github_username: goldenson

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-target-blank
  - jekyll-last-modified-at
  - jekyll_sqlite

relative_links:
  enabled: true
  collections: true

exclude: ["Rakefile"]

sqlite:
  - data: crossfits
    file: _data/database.sqlite
    query: SELECT * from trainings
