### Config
title: Maxime Orefice
email: orefice.maxime@gmail.com
description: >-
  Humain en construction. Curieux, débrouillard et déterminé.
  Derrière chaque erreur se cache une grande leçon de vie.

# Permalinks
permalink: pretty

# About
url: "https://goldenson.dev"
twitter_username: goldenson_
github_username: goldenson

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-target-blank

relative_links:
  enabled: true
  collections: true

google_analytics: UA-152637440-1

exclude: ["Rakefile"]
